# .github/workflows/zap_scan.yml
name: ZAP Scan

on:
  push:
    branches: [ "main" ] # Adjust this to your main branch name

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Run FastAPI application in the background
        run: uvicorn main:app --host 0.0.0.0 --port 8000 &

      - name: Wait for application to start
        run: sleep 5

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.0
        with:
          target: http://localhost:8000
          rules_file: .zap_rules.tsv # Optional: Define specific rules
          report_file: zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html